-- ===========================================
-- Migration:     create_event_chat_messages_table
--
-- Description:
--   - Creates the 'event_chat_messages' table
--   - Adds RLS policies for inserting and deleting messages
-- ===========================================

create table public.event_chat_messages (
    id bigint generated by default as identity primary key,
    event_id bigint references public.events on delete cascade not null,
    sender_id uuid references auth.users on delete cascade not null,
    sent_at timestamp with time zone default now(),
    message text not null,
    attachments text[] not null default array[]::text[]
);

comment on table public.event_chat_messages is 'Messages that belong to a specific event chat';

create policy "Only attending users can send messages" on public.event_chat_messages
    for insert
    with check (
        auth.uid() is not null
        and exists (
            select 1
            from public.event_joins
            where event_joins.event_id = event_chat_messages.event_id
            and event_joins.user_id = auth.uid()
        )
    );

create policy "Only sender can delete message" on public.event_chat_messages
    for delete
    using (auth.uid() is not null and auth.uid() = sender_id);

