-- ===========================================
-- Migration:     create_events_table
--
-- Description:
--   - Creates the 'events' table to store all DropIn events
--   - Defines fields for metadata, location, scheduling, and settings
--   - Includes constraints, default values, and a custom enum 'event_status'
-- ===========================================

-- Events table

create table public.events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    title text not null,
    description text not null,
    image_paths text[] not null default array['default.event.thumbnail'],
    user_id uuid references auth.users on delete cascade not null default auth.uid(),
    start timestamp with time zone not null,
    "end" timestamp with time zone not null,
    latitude double precision not null check (latitude >= -90 and latitude <= 90),
    longitude double precision not null check (longitude >= -180 and longitude <= 180),
    slot_limit integer not null check (slot_limit >= 1),
    slots_taken integer not null default 0 check (slots_taken <= slot_limit),
    age_restricted boolean not null default false,
    chat_enabled boolean not null default true
);


comment on table public.events is 'All dropin events';
